// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tranhoangkhai_project1.Data;

#nullable disable

namespace tranhoangkhai_project1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240319163338_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tranhoangkhai_project1.Models.DonViTinhModel", b =>
                {
                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ten_Don_Vi_Tinh");

                    b.ToTable("tbl_DM_Don_Vi_Tinh");

                    b.HasData(
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_01",
                            Ghi_Chu = "Ghi chu 1"
                        },
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_02",
                            Ghi_Chu = "Ghi chu 2"
                        },
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_03",
                            Ghi_Chu = "Ghi chu 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
