// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tranhoangkhai_project1.Data;

#nullable disable

namespace tranhoangkhai_project1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240320081528_addTblSanPham")]
    partial class addTblSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tranhoangkhai_project1.Models.DonViTinhModel", b =>
                {
                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ten_Don_Vi_Tinh");

                    b.ToTable("tbl_DM_Don_Vi_Tinh");

                    b.HasData(
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_01",
                            Ghi_Chu = "Ghi chu 1"
                        },
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_02",
                            Ghi_Chu = "Ghi chu 2"
                        },
                        new
                        {
                            Ten_Don_Vi_Tinh = "dvt_03",
                            Ghi_Chu = "Ghi chu 3"
                        });
                });

            modelBuilder.Entity("tranhoangkhai_project1.Models.LoaiSanPhamModel", b =>
                {
                    b.Property<string>("Ma_LSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_LSP");

                    b.ToTable("tbl_DM_Loai_San_Pham");

                    b.HasData(
                        new
                        {
                            Ma_LSP = "lsp_01",
                            Ghi_Chu = "Ghi chu 1",
                            Ten_LSP = "Loai 1"
                        },
                        new
                        {
                            Ma_LSP = "lsp_02",
                            Ghi_Chu = "Ghi chu 2",
                            Ten_LSP = "Loai 2"
                        },
                        new
                        {
                            Ma_LSP = "lsp_03",
                            Ghi_Chu = "Ghi chu 3",
                            Ten_LSP = "Loai 3"
                        });
                });

            modelBuilder.Entity("tranhoangkhai_project1.Models.SanPhamModel", b =>
                {
                    b.Property<string>("Ma_San_Pham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Don_Vi_Tinh_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai_San_Pham_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ma_San_Pham");

                    b.ToTable("tbl_DM_San_Pham");

                    b.HasData(
                        new
                        {
                            Ma_San_Pham = "sp_01",
                            Don_Vi_Tinh_ID = "dvt_01",
                            Ghi_Chu = "Ghi chu 1",
                            Loai_San_Pham_ID = "lsp_01",
                            Ten_San_Pham = "San Pham 1"
                        },
                        new
                        {
                            Ma_San_Pham = "sp_02",
                            Don_Vi_Tinh_ID = "dvt_02",
                            Ghi_Chu = "Ghi chu 2",
                            Loai_San_Pham_ID = "lsp_02",
                            Ten_San_Pham = "San Pham 1 2"
                        },
                        new
                        {
                            Ma_San_Pham = "sp_03",
                            Don_Vi_Tinh_ID = "dvt_02",
                            Ghi_Chu = "Ghi chu 3",
                            Loai_San_Pham_ID = "lsp_03",
                            Ten_San_Pham = "San Pham 1 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
